{"name": "Проверка создания двух одинаковых курьеров", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <test_courier.TestCreatingCourier object at 0x000002B7CDA351C0>\nreg_new_courier_return_login_pass_del_this_courier = (<Response [201]>, ['txasfymnks', 'efrddbjymd', 'ugwxqcqexs'])\n\n    @allure.title('Проверка создания двух одинаковых курьеров')\n    @allure.description('Если создать курьера с логином, который уже есть, возвращается ошибка')\n    def test_creating_courier_courier_already_exists_error_message(self, reg_new_courier_return_login_pass_del_this_courier):\n        login_pass = reg_new_courier_return_login_pass_del_this_courier[1]\n        same_login_pass = {\"login\": login_pass[0], \"password\": login_pass[1]}\n        response = requests.post(Constants.MAIN_URL + APICourierUrls.CREATING_COURIER_URL, data=same_login_pass)\n>       assert response.status_code == 409 and response.json()[\"message\"] == 'Этот логин уже используется'\nE       AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE        +  where 409 = <Response [409]>.status_code\nE         \nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.)\n\ntests\\test_courier.py:24: AssertionError"}, "description": "Если создать курьера с логином, который уже есть, возвращается ошибка", "attachments": [{"name": "stdout", "source": "2fb99b13-3d0d-41ad-b245-88de01730df9-attachment.txt", "type": "text/plain"}], "start": 1721921918272, "stop": 1721921918459, "uuid": "2e6cec37-2f72-4e6c-9857-1a8d75a44978", "historyId": "fa636c04ed6c451d8c96c7e9fcf41393", "testCaseId": "fa636c04ed6c451d8c96c7e9fcf41393", "fullName": "tests.test_courier.TestCreatingCourier#test_creating_courier_courier_already_exists_error_message", "labels": [{"name": "epic", "value": "test_creating_courier"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCreatingCourier"}, {"name": "host", "value": "DESKTOP-619AU3M"}, {"name": "thread", "value": "8372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}